// PROJECT 11: Enterprise Customer Master Data Management
// Hybrid SCD Strategies (Type 1 + Type 2 + Type 3 + Type 6)
// Topic: 4.2D

// TASK 1: CREATE DATABASE AND SCHEMA

CREATE OR REPLACE WAREHOUSE PROJECT11_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT11_WH;

CREATE OR REPLACE DATABASE HYBRID_SCD;

USE DATABASE HYBRID_SCD;

CREATE OR REPLACE SCHEMA PUBLIC;
USE SCHEMA PUBLIC;

// TASK 2: CREATE HYBRID DIMENSION TABLE

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY NUMBER IDENTITY(1,1),
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

// TASK 3: LOAD INITIAL DIMENSION DATA

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(101, 'Amit Sharma', 'Hyderabad', NULL, 'Telangana', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(102, 'Priya Reddy', 'Warangal', NULL, 'Telangana', 'Gold', NULL, 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(103, 'Rahul Verma', 'Vijayawada', NULL, 'Andhra Pradesh', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(104, 'Neha Patel', 'Hyderabad', NULL, 'Telangana', 'Gold', NULL, 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(105, 'Arjun Gupta', 'Nagpur', NULL, 'Maharashtra', 'Bronze', NULL, 'Bronze', 'Regular', '2026-01-01', '9999-12-31', TRUE);

SELECT 'Initial Hybrid Dimension Data Loaded Successfully' AS STATUS;
SELECT COUNT(*) AS TOTAL_RECORDS FROM DIM_CUSTOMER_HYBRID;
SELECT COUNT(*) AS CURRENT_RECORDS FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE;

// TASK 4: DISPLAY INITIAL DIMENSION STATE

SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

// TASK 5: APPLY HYBRID UPDATES

// Step 1: Expire active versions of updated customers

// Customer 101
UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = '2026-03-31', IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE;

// Customer 103
UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = '2026-04-04', IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE;

// Customer 104
UPDATE DIM_CUSTOMER_HYBRID
SET EXPIRY_DATE = '2026-04-09', IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE;

// Step 2: Insert new active versions

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Hyderabad', 'Karnataka', 'Gold', 'Silver', 'Gold', 'Premium', '2026-04-01', '9999-12-31', TRUE),
(103, 'Rahul Verma', 'Chennai', 'Vijayawada', 'Tamil Nadu', 'Gold', 'Silver', 'Gold', 'Premium', '2026-04-05', '9999-12-31', TRUE),
(104, 'Neha Patel', 'Hyderabad', NULL, 'Telangana', 'Platinum', 'Gold', 'Platinum', 'Premium', '2026-04-10', '9999-12-31', TRUE);

// Step 3: Synchronize global attributes across ALL rows for each customer
// Type 1 (State): Already set in new row
// Type 3 (City/Previous_City): Update all rows with current city and previous city
// Type 6 (Current/Previous Membership): Update all rows

// Customer 101: Sync city, state, current/previous membership across all rows
UPDATE DIM_CUSTOMER_HYBRID
SET CITY = 'Bengaluru',
    PREVIOUS_CITY = 'Hyderabad',
    STATE = 'Karnataka',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;

// Customer 103: Sync city, state, current/previous membership across all rows
UPDATE DIM_CUSTOMER_HYBRID
SET CITY = 'Chennai',
    PREVIOUS_CITY = 'Vijayawada',
    STATE = 'Tamil Nadu',
    CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;

// Customer 104: Sync current/previous membership across all rows
UPDATE DIM_CUSTOMER_HYBRID
SET CURRENT_MEMBERSHIP = 'Platinum',
    PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;

SELECT 'Hybrid SCD Updates Applied Successfully' AS STATUS;
SELECT COUNT(*) AS TOTAL_RECORDS FROM DIM_CUSTOMER_HYBRID;
SELECT COUNT(*) AS CURRENT_RECORDS FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE;
SELECT COUNT(*) AS HISTORICAL_RECORDS FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE;

// TASK 6: DISPLAY COMPLETE DIMENSION HISTORY

SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

// TASK 7: DISPLAY ACTIVE CUSTOMER REPORT

SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

// TASK 8: POINT-IN-TIME HISTORICAL QUERY
// What was Customer 101's membership, segment, and city on March 15, 2026?

SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY,
    HISTORICAL_MEMBERSHIP, SEGMENT,
    EFFECTIVE_DATE, EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

// TASK 9: METRIC VALIDATION AND RECORD COUNTS

SELECT 'TOTAL RECORD COUNT' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT RECORD COUNT', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL RECORD COUNT', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE;
