// PROJECT 4 : RETAIL DATA WAREHOUSE
// DIMENSIONAL MODELING
// STEPS 1 TO 7

// STEP 1 : CREATE VIRTUAL WAREHOUSE

CREATE OR REPLACE WAREHOUSE RETAIL_DW_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RETAIL_DW_WH;

// STEP 2 : CREATE DATABASE AND SCHEMAS

CREATE OR REPLACE DATABASE RETAIL_DW;

USE DATABASE RETAIL_DW;

CREATE OR REPLACE SCHEMA STAGING;

CREATE OR REPLACE SCHEMA ANALYTICS;

// STEP 3 : CREATE INTERNAL STAGE

USE SCHEMA STAGING;

CREATE OR REPLACE STAGE RETAIL_STAGE;

SHOW STAGES IN SCHEMA RETAIL_DW.STAGING;

// STEP 3.1 : CREATE CSV FILE FORMAT

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE;

SHOW FILE FORMATS IN SCHEMA RETAIL_DW.STAGING;

// STEP 3.2 : CREATE STAGING TABLES

// STG_CUSTOMERS

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

// STG_PRODUCTS

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

// STG_BRANCHES

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

// STG_CALENDAR

CREATE OR REPLACE TABLE CALENDAR (
    DATE_ID NUMBER,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(10)
);

// STG_SALES

CREATE OR REPLACE TABLE SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);

// VERIFY STAGING TABLES

SHOW TABLES IN SCHEMA RETAIL_DW.STAGING;

// STEP 4 : CREATE DIMENSION TABLES

USE SCHEMA ANALYTICS;

// DIM_CUSTOMER

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

// DIM_PRODUCT

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

// DIM_BRANCH

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

// DIM_DATE

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR NUMBER,
    IS_WEEKEND VARCHAR(10)
);

// STEP 5 : CREATE FACT TABLE

CREATE OR REPLACE TABLE FACT_SALES (

    SALE_ID NUMBER PRIMARY KEY,

    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,

    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);

// STEP 6 : LOAD DIMENSION TABLES

// LOAD CUSTOMER DIMENSION

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM STAGING.CUSTOMERS;

// LOAD PRODUCT DIMENSION

INSERT INTO DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    PRICE
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    PRICE
FROM STAGING.PRODUCTS;

// LOAD BRANCH DIMENSION

INSERT INTO DIM_BRANCH (
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION,
    MANAGER_NAME
)
SELECT
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION,
    MANAGER_NAME
FROM STAGING.BRANCHES;

// LOAD DATE DIMENSION

INSERT INTO DIM_DATE (
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
)
SELECT
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
FROM STAGING.CALENDAR;

// LOAD FACT SALES

INSERT INTO FACT_SALES (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM STAGING.SALES;

// STEP 6.1 : VERIFY ROW COUNTS

// STAGING COUNTS

SELECT COUNT(*) AS CUSTOMER_COUNT
FROM STAGING.CUSTOMERS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM STAGING.PRODUCTS;

SELECT COUNT(*) AS BRANCH_COUNT
FROM STAGING.BRANCHES;

SELECT COUNT(*) AS DATE_COUNT
FROM STAGING.CALENDAR;

SELECT COUNT(*) AS SALES_COUNT
FROM STAGING.SALES;

// DIMENSION COUNTS

SELECT COUNT(*) AS DIM_CUSTOMER_COUNT
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS DIM_PRODUCT_COUNT
FROM DIM_PRODUCT;

SELECT COUNT(*) AS DIM_BRANCH_COUNT
FROM DIM_BRANCH;

SELECT COUNT(*) AS DIM_DATE_COUNT
FROM DIM_DATE;

// FACT COUNT

SELECT COUNT(*) AS FACT_SALES_COUNT
FROM FACT_SALES;

// STEP 6.2 : VIEW DATA

SELECT *
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

SELECT *
FROM DIM_PRODUCT
ORDER BY PRODUCT_ID;

SELECT *
FROM DIM_BRANCH
ORDER BY BRANCH_ID;

SELECT *
FROM DIM_DATE
ORDER BY DATE_ID;

SELECT *
FROM FACT_SALES
ORDER BY SALE_ID;

// STEP 7 : RELATIONSHIP VALIDATION

// 7.1 CUSTOMER -> FACT_SALES
// DIM_CUSTOMER 1 : M FACT_SALES

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(F.SALE_ID) AS SALES_COUNT
FROM DIM_CUSTOMER C
LEFT JOIN FACT_SALES F
    ON C.CUSTOMER_ID = F.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY
    C.CUSTOMER_ID;

// 7.2 PRODUCT -> FACT_SALES
// DIM_PRODUCT 1 : M FACT_SALES

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COUNT(F.SALE_ID) AS SALES_COUNT
FROM DIM_PRODUCT P
LEFT JOIN FACT_SALES F
    ON P.PRODUCT_ID = F.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY
    P.PRODUCT_ID;

// 7.3 BRANCH -> FACT_SALES
// DIM_BRANCH 1 : M FACT_SALES

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    COUNT(F.SALE_ID) AS SALES_COUNT
FROM DIM_BRANCH B
LEFT JOIN FACT_SALES F
    ON B.BRANCH_ID = F.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY
    B.BRANCH_ID;

// 7.4 DATE -> FACT_SALES
// DIM_DATE 1 : M FACT_SALES

SELECT
    D.DATE_ID,
    D.DATE,
    COUNT(F.SALE_ID) AS SALES_COUNT
FROM DIM_DATE D
LEFT JOIN FACT_SALES F
    ON D.DATE_ID = F.DATE_ID
GROUP BY
    D.DATE_ID,
    D.DATE
ORDER BY
    D.DATE_ID;

// STEP 7.5 : CHECK FOR ORPHAN CUSTOMER KEYS

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

// STEP 7.6 : CHECK FOR ORPHAN PRODUCT KEYS

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

// STEP 7.7 : CHECK FOR ORPHAN BRANCH KEYS

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;

// STEP 7.8 : CHECK FOR ORPHAN DATE KEYS

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;

// STEP 7.9 : CHECK COMPLETE STAR-SCHEMA JOIN

SELECT
    F.SALE_ID,

    C.CUSTOMER_NAME,

    P.PRODUCT_NAME,
    P.CATEGORY,

    B.BRANCH_NAME,
    B.STATE,
    B.REGION,

    D.DATE,
    D.MONTH,
    D.QUARTER,
    D.YEAR,

    F.QUANTITY,
    F.TOTAL_AMOUNT

FROM FACT_SALES F

JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID

JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID

JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID

JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID

ORDER BY F.SALE_ID;

// FINAL OBJECT CHECK

SHOW TABLES IN SCHEMA RETAIL_DW.ANALYTICS;
