// PROJECT 15: Cross-Border Logistics & Fleet Telematics Lakehouse Platform
// Modules: 4.4a (Schema-on-Read vs Schema-on-Write) & 4.4b (Medallion & Time-Travel)

// TASK 1: BRONZE DATA LAKE INGESTION & SCHEMA-ON-READ EXPLORATION

CREATE OR REPLACE WAREHOUSE PROJECT15_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT15_WH;

CREATE OR REPLACE DATABASE LOGISTICS_LAKEHOUSE_DB;

USE DATABASE LOGISTICS_LAKEHOUSE_DB;

CREATE OR REPLACE SCHEMA FLEET_CORE;
USE SCHEMA FLEET_CORE;

// Bronze Layer table
CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS (
    INGEST_ID NUMBER IDENTITY(1,1),
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

// Ingest Batch 1 (Standard Telematics & Delivery Payloads)
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-801","payload_type":"TELEMATICS","timestamp":"2026-08-01T06:00:00Z","data":{"trip_id":"TRP-101","vehicle_id":"TRK-9001","driver_name":"John Doe","distance_km":450.0,"fuel_consumed_liters":120.0,"speed_avg":75.0}}');
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-802","payload_type":"CUSTOMS","timestamp":"2026-08-01T06:30:00Z","data":{"shipment_id":"SHP-5001","vehicle_id":"TRK-9001","destination_country":"CAN","declared_value":85000.00,"duty_pct":5.0,"clearance_status":"CLEARED"}}');
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-803","payload_type":"TELEMATICS","timestamp":"2026-08-01T07:00:00Z","data":{"trip_id":"TRP-102","vehicle_id":"TRK-9002","driver_name":"Jane Smith","distance_km":620.0,"fuel_consumed_liters":180.0,"speed_avg":82.0}}');
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-804","payload_type":"CUSTOMS","timestamp":"2026-08-01T07:45:00Z","data":{"shipment_id":"SHP-5002","vehicle_id":"TRK-9002","destination_country":"MEX","declared_value":42000.00,"duty_pct":7.5,"clearance_status":"CLEARED"}}');

// Ingest Batch 2 (Schema Evolution — new fields: driver_fatigue_score, border_clearance_code)
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-805","payload_type":"TELEMATICS","timestamp":"2026-08-01T08:15:00Z","data":{"trip_id":"TRP-103","vehicle_id":"TRK-9003","driver_name":"Robert Brown","distance_km":310.0,"fuel_consumed_liters":95.0,"speed_avg":68.0,"driver_fatigue_score":1.2}}');
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-806","payload_type":"CUSTOMS","timestamp":"2026-08-01T08:30:00Z","data":{"shipment_id":"SHP-5003","vehicle_id":"TRK-9003","destination_country":"CAN","declared_value":120000.00,"duty_pct":4.0,"clearance_status":"CLEARED","border_clearance_code":"FAST_PASS_01"}}');
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-807","payload_type":"CUSTOMS","timestamp":"2026-08-01T09:00:00Z","data":{"shipment_id":"SHP-5004","vehicle_id":"TRK-9001","destination_country":"MEX","declared_value":15000.00,"duty_pct":7.5,"clearance_status":"HELD_INSPECTION","border_clearance_code":null}}');

// Ingest Batch 3 (Faulty reading + Corrupted payload)
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT PARSE_JSON('{"payload_id":"PL-808","payload_type":"TELEMATICS","timestamp":"2026-08-01T09:30:00Z","data":{"trip_id":"TRP-104","vehicle_id":"TRK-9004","driver_name":"Alice Green","distance_km":0.0,"fuel_consumed_liters":0.0,"speed_avg":0.0,"driver_fatigue_score":0.0}}');

// Corrupted payload (stored as raw variant string)
INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD) SELECT TO_VARIANT('MALFORMED_IOT_SENSOR_BINARY_BURST_DATA_ERR');

// Verify Bronze count
SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_IOT_STREAMS;

// Schema-on-Read exploration query
SELECT
    RAW_PAYLOAD:payload_id::VARCHAR AS PAYLOAD_ID,
    RAW_PAYLOAD:payload_type::VARCHAR AS PAYLOAD_TYPE,
    RAW_PAYLOAD:timestamp::TIMESTAMP AS EVENT_TIME,
    RAW_PAYLOAD:data.vehicle_id::VARCHAR AS VEHICLE_ID,
    RAW_PAYLOAD:data.shipment_id::VARCHAR AS SHIPMENT_ID,
    RAW_PAYLOAD:data.declared_value::NUMBER(12,2) AS DECLARED_VALUE
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_id IS NOT NULL
ORDER BY EVENT_TIME;

// TASK 2: DEAD-LETTER QUEUE QUARANTINE STRATEGY

CREATE OR REPLACE TABLE QUARANTINE_IOT_PAYLOADS (
    QUARANTINE_ID NUMBER IDENTITY(1,1),
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR(100),
    QUARANTINE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

// Identify and quarantine malformed records
INSERT INTO QUARANTINE_IOT_PAYLOADS (RAW_RECORD_TEXT, REASON)
SELECT
    RAW_PAYLOAD::VARCHAR,
    'MALFORMED_JSON_BODY'
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_id IS NULL;

// Verify quarantine
SELECT QUARANTINE_ID, RAW_RECORD_TEXT, REASON FROM QUARANTINE_IOT_PAYLOADS;

// Remove quarantined records from Bronze
DELETE FROM BRONZE_IOT_STREAMS WHERE RAW_PAYLOAD:payload_id IS NULL;

// TASK 3: SILVER LAYER ETL — CUSTOMS CLEARANCE

CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE (
    SHIPMENT_ID VARCHAR(50),
    PAYLOAD_ID VARCHAR(50),
    VEHICLE_ID VARCHAR(50),
    DESTINATION_COUNTRY VARCHAR(10),
    DECLARED_VALUE NUMBER(12,2),
    DUTY_PCT NUMBER(5,2),
    DUTY_AMOUNT_DUE NUMBER(12,2),
    BORDER_CODE VARCHAR(50),
    CLEARANCE_STATUS VARCHAR(30)
);

INSERT INTO SILVER_CUSTOMS_CLEARANCE
SELECT
    RAW_PAYLOAD:data.shipment_id::VARCHAR,
    RAW_PAYLOAD:payload_id::VARCHAR,
    RAW_PAYLOAD:data.vehicle_id::VARCHAR,
    RAW_PAYLOAD:data.destination_country::VARCHAR,
    RAW_PAYLOAD:data.declared_value::NUMBER(12,2),
    RAW_PAYLOAD:data.duty_pct::NUMBER(5,2),
    ROUND(RAW_PAYLOAD:data.declared_value::NUMBER(12,2) * (RAW_PAYLOAD:data.duty_pct::NUMBER(5,2) / 100), 2),
    RAW_PAYLOAD:data.border_clearance_code::VARCHAR,
    RAW_PAYLOAD:data.clearance_status::VARCHAR
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS';

// Verify Silver layer
SELECT SHIPMENT_ID, VEHICLE_ID, DESTINATION_COUNTRY, DECLARED_VALUE, DUTY_PCT, DUTY_AMOUNT_DUE, BORDER_CODE, CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;

// TASK 4: GOLD LAYER STRATEGIC AGGREGATIONS (CLEARED shipments only)

CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY (
    DESTINATION_COUNTRY VARCHAR(10),
    TOTAL_CLEARED_VALUE NUMBER(12,2),
    TOTAL_DUTIES_COLLECTED NUMBER(12,2),
    AVG_DUTY_RATE_PCT NUMBER(5,2),
    CLEARED_SHIPMENTS NUMBER
);

INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY
SELECT
    DESTINATION_COUNTRY,
    SUM(DECLARED_VALUE),
    SUM(DUTY_AMOUNT_DUE),
    ROUND(AVG(DUTY_PCT), 2),
    COUNT(*)
FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'
GROUP BY DESTINATION_COUNTRY;

// Verify Gold layer
SELECT * FROM GOLD_COUNTRY_DUTY_SUMMARY ORDER BY DESTINATION_COUNTRY;

// TASK 5: DISASTER RECOVERY VIA SNOWFLAKE TIME-TRAVEL

// Step 1: Simulate corruption — set all CAN shipments to REJECTED
UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DESTINATION_COUNTRY = 'CAN';

// Capture the corruption query ID
SET corruption_qid = (SELECT LAST_QUERY_ID());

// Verify corruption
SELECT SHIPMENT_ID, DESTINATION_COUNTRY, CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE DESTINATION_COUNTRY = 'CAN';

// Step 2: Time-Travel query to inspect pre-corruption state
SELECT SHIPMENT_ID, DESTINATION_COUNTRY, CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE BEFORE (STATEMENT => $corruption_qid)
WHERE DESTINATION_COUNTRY = 'CAN';

// Step 3: Recovery — restore original statuses
MERGE INTO SILVER_CUSTOMS_CLEARANCE AS target
USING (
    SELECT SHIPMENT_ID, CLEARANCE_STATUS
    FROM SILVER_CUSTOMS_CLEARANCE BEFORE (STATEMENT => $corruption_qid)
    WHERE DESTINATION_COUNTRY = 'CAN'
) AS source
ON target.SHIPMENT_ID = source.SHIPMENT_ID
WHEN MATCHED THEN UPDATE SET target.CLEARANCE_STATUS = source.CLEARANCE_STATUS;

// Post-recovery audit
SELECT
    DESTINATION_COUNTRY,
    SUM(CASE WHEN CLEARANCE_STATUS = 'CLEARED' THEN 1 ELSE 0 END) AS CLEARED_COUNT,
    SUM(CASE WHEN CLEARANCE_STATUS = 'REJECTED' THEN 1 ELSE 0 END) AS REJECTED_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY DESTINATION_COUNTRY
ORDER BY DESTINATION_COUNTRY;

// TASK 6: END-TO-END PIPELINE LINEAGE & RECONCILIATION AUDIT

SELECT
    (SELECT SUM(RAW_PAYLOAD:data.declared_value::NUMBER(12,2))
     FROM BRONZE_IOT_STREAMS
     WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS') AS BRONZE_GROSS_TOTAL,
    (SELECT SUM(DECLARED_VALUE)
     FROM SILVER_CUSTOMS_CLEARANCE) AS SILVER_GROSS_TOTAL,
    (SELECT SUM(TOTAL_CLEARED_VALUE)
     FROM GOLD_COUNTRY_DUTY_SUMMARY) AS GOLD_GROSS_TOTAL,
    CASE
        WHEN (SELECT SUM(RAW_PAYLOAD:data.declared_value::NUMBER(12,2))
              FROM BRONZE_IOT_STREAMS
              WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS')
           = (SELECT SUM(DECLARED_VALUE) FROM SILVER_CUSTOMS_CLEARANCE)
        THEN 'TRUE'
        ELSE 'FALSE'
    END AS RECONCILED_FLAG;