// PROJECT 10: Customer Membership History
// SCD Type 3 and Type 6 Implementation
// Topic: 4.2C

// TASK 1: CREATE DATABASE AND SCHEMA

CREATE OR REPLACE WAREHOUSE PROJECT10_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT10_WH;

CREATE OR REPLACE DATABASE SCD_TYPE36;

USE DATABASE SCD_TYPE36;

CREATE OR REPLACE SCHEMA PUBLIC;
USE SCHEMA PUBLIC;

// TASK 2: CREATE SCD TYPE 3 DIMENSION

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3 (
    CUSTOMER_KEY NUMBER IDENTITY(1,1),
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

// TASK 3: LOAD INITIAL TYPE 3 DATA

INSERT INTO DIM_CUSTOMER_TYPE3 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, SEGMENT)
VALUES
(101, 'Amit Sharma', 'Hyderabad', 'Telangana', 'Silver', NULL, 'Regular'),
(102, 'Priya Reddy', 'Warangal', 'Telangana', 'Gold', NULL, 'Premium'),
(103, 'Rahul Verma', 'Vijayawada', 'Andhra Pradesh', 'Silver', NULL, 'Regular'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Gold', NULL, 'Premium'),
(105, 'Arjun Gupta', 'Nagpur', 'Maharashtra', 'Bronze', NULL, 'Regular');

SELECT 'Initial Type 3 Records Loaded Successfully' AS STATUS;
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM DIM_CUSTOMER_TYPE3;

// TASK 4: DISPLAY INITIAL TYPE 3 DATA

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

// TASK 5 & 6: APPLY SCD TYPE 3 CHANGES

// Create staging table for updates
CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

INSERT INTO CUSTOMER_UPDATES VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10');

// Apply Type 3: Move current to previous, set new current
MERGE INTO DIM_CUSTOMER_TYPE3 T
USING CUSTOMER_UPDATES U
ON T.CUSTOMER_ID = U.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    T.PREVIOUS_MEMBERSHIP = T.CURRENT_MEMBERSHIP,
    T.CURRENT_MEMBERSHIP = U.MEMBERSHIP,
    T.CITY = U.CITY,
    T.STATE = U.STATE,
    T.SEGMENT = U.SEGMENT;

// TASK 7: TYPE 3 FINAL REPORT

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

// TASK 8: DEMONSTRATE TYPE 3 — CUSTOMER 101

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

// TASK 9: CREATE SCD TYPE 6 DIMENSION

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY NUMBER IDENTITY(1,1),
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

// TASK 10: LOAD INITIAL TYPE 6 RECORDS

INSERT INTO DIM_CUSTOMER_TYPE6
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(101, 'Amit Sharma', 'Hyderabad', 'Telangana', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(102, 'Priya Reddy', 'Warangal', 'Telangana', 'Gold', NULL, 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(103, 'Rahul Verma', 'Vijayawada', 'Andhra Pradesh', 'Silver', NULL, 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Gold', NULL, 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(105, 'Arjun Gupta', 'Nagpur', 'Maharashtra', 'Bronze', NULL, 'Bronze', 'Regular', '2026-01-01', '9999-12-31', TRUE);

SELECT 'Initial Type 6 Records Loaded Successfully' AS STATUS;
SELECT COUNT(*) AS TOTAL_RECORDS FROM DIM_CUSTOMER_TYPE6;
SELECT COUNT(*) AS CURRENT_RECORDS FROM DIM_CUSTOMER_TYPE6 WHERE IS_CURRENT = TRUE;

// TASK 11: APPLY TYPE 6 CHANGE — CUSTOMER 101

// Step 1: Expire old record
UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

// Step 2: Insert new version
INSERT INTO DIM_CUSTOMER_TYPE6
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Silver', 'Gold', 'Premium', '2026-04-01', '9999-12-31', TRUE);

// Step 3: Update CURRENT_MEMBERSHIP on all rows for this customer
UPDATE DIM_CUSTOMER_TYPE6
SET CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;

// TASK 12: APPLY REMAINING TYPE 6 CHANGES

// Customer 103: Silver → Gold, Effective 2026-04-05
UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Silver', 'Gold', 'Premium', '2026-04-05', '9999-12-31', TRUE);

UPDATE DIM_CUSTOMER_TYPE6
SET CURRENT_MEMBERSHIP = 'Gold',
    PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;

// Customer 104: Gold → Platinum, Effective 2026-04-10
UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Gold', 'Platinum', 'Premium', '2026-04-10', '9999-12-31', TRUE);

UPDATE DIM_CUSTOMER_TYPE6
SET CURRENT_MEMBERSHIP = 'Platinum',
    PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;

// TASK 13: DISPLAY COMPLETE TYPE 6 HISTORY

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

// TASK 14: CURRENT CUSTOMER REPORT

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

// TASK 15: POINT-IN-TIME HISTORICAL QUERY
// What was Customer 101's membership on March 15, 2026?

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

// TASK 16: TYPE 3 vs TYPE 6 COMPARISON

SELECT 'TYPE 3' AS SCD_TYPE, CUSTOMER_ID, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP,
       NULL AS EFFECTIVE_DATE, NULL AS EXPIRY_DATE, NULL AS IS_CURRENT
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101

UNION ALL

SELECT 'TYPE 6', CUSTOMER_ID, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP,
       EFFECTIVE_DATE::VARCHAR, EXPIRY_DATE::VARCHAR, IS_CURRENT::VARCHAR
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
ORDER BY SCD_TYPE, EFFECTIVE_DATE;

// TASK 17: RECORD COUNT VALIDATION

SELECT 'SCD TYPE 3 RECORD COUNT' AS METRIC, COUNT(*) AS VALUE FROM DIM_CUSTOMER_TYPE3
UNION ALL
SELECT 'SCD TYPE 6 RECORD COUNT', COUNT(*) FROM DIM_CUSTOMER_TYPE6
UNION ALL
SELECT 'SCD TYPE 6 CURRENT RECORDS', COUNT(*) FROM DIM_CUSTOMER_TYPE6 WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'SCD TYPE 6 HISTORICAL RECORDS', COUNT(*) FROM DIM_CUSTOMER_TYPE6 WHERE IS_CURRENT = FALSE;
