// PROJECT 13B: Healthcare Analytics Warehouse
// Star Schema vs Snowflake Schema
// Modules: 4.3a (Star Schema), 4.3b (Snowflake Schema)

// TASK 1: CREATE DATABASE AND SCHEMA

CREATE OR REPLACE WAREHOUSE PROJECT13B_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT13B_WH;

CREATE OR REPLACE DATABASE HEALTHCARE_DW;

USE DATABASE HEALTHCARE_DW;

CREATE OR REPLACE SCHEMA SCHEMA_COMPARE_LAB;
USE SCHEMA SCHEMA_COMPARE_LAB;

// TASK 2: CREATE STAR SCHEMA - DENORMALIZED HOSPITAL DIMENSION

CREATE OR REPLACE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

// TASK 3: CREATE STAR SCHEMA - DENORMALIZED TREATMENT DIMENSION

CREATE OR REPLACE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);

// TASK 4: LOAD STAR SCHEMA DIMENSION DATA

INSERT INTO STAR_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_NAME, NETWORK_DIRECTOR) VALUES
(1001, 'Apollo Jubilee Hills', 'Hyderabad', 'Telangana', 'Apollo Healthcare Group', 'Dr. Ramesh'),
(1002, 'Apollo Reach', 'Warangal', 'Telangana', 'Apollo Healthcare Group', 'Dr. Ramesh'),
(2001, 'Manipal Central', 'Bengaluru', 'Karnataka', 'Manipal Hospitals', 'Dr. Priya');

INSERT INTO STAR_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, DIAGNOSIS_GROUP_NAME, STANDARD_COST) VALUES
(501, 'Coronary Angioplasty', 'Cardiology', 150000.00),
(502, 'Knee Replacement', 'Orthopedics', 220000.00),
(503, 'Appendectomy', 'General Surgery', 45000.00);

// TASK 5: BUILD & LOAD STAR FACT TABLE

CREATE OR REPLACE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),
    TREATMENT_KEY NUMBER REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY),
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2)
);

INSERT INTO STAR_FACT_CLAIMS (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT C.CLAIM_ID, C.CLAIM_DATE, C.PATIENT_ID, H.HOSPITAL_KEY, T.TREATMENT_KEY, C.CLAIMED_AMOUNT, C.APPROVED_AMOUNT
FROM (
    SELECT 'CLM-9001' AS CLAIM_ID, '2026-06-01'::DATE AS CLAIM_DATE, 701 AS PATIENT_ID, 1001 AS HOSPITAL_ID, 501 AS TREATMENT_ID, 160000.00 AS CLAIMED_AMOUNT, 150000.00 AS APPROVED_AMOUNT
    UNION ALL SELECT 'CLM-9002', '2026-06-05', 702, 1002, 503, 50000.00, 45000.00
    UNION ALL SELECT 'CLM-9003', '2026-06-10', 703, 2001, 502, 230000.00, 220000.00
    UNION ALL SELECT 'CLM-9004', '2026-06-12', 701, 1001, 503, 48000.00, 45000.00
) C
JOIN STAR_DIM_HOSPITAL H ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT T ON C.TREATMENT_ID = T.TREATMENT_ID;

// TASK 6: BUILD SNOWFLAKE SCHEMA - HOSPITAL HIERARCHY

CREATE OR REPLACE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_KEY NUMBER REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);

// TASK 7: BUILD SNOWFLAKE SCHEMA - TREATMENT HIERARCHY

CREATE OR REPLACE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    DIAGNOSIS_GROUP_ID VARCHAR(20),
    DIAGNOSIS_GROUP_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    STANDARD_COST NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY NUMBER REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);

// TASK 8: POPULATE SNOWFLAKE SCHEMA DIMENSIONS

// Networks
INSERT INTO SNOW_DIM_NETWORK (NETWORK_ID, NETWORK_NAME, NETWORK_DIRECTOR) VALUES
(10, 'Apollo Healthcare Group', 'Dr. Ramesh'),
(20, 'Manipal Hospitals', 'Dr. Priya');

// Hospitals (Apollo=key 1, Manipal=key 2)
INSERT INTO SNOW_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_KEY) VALUES
(1001, 'Apollo Jubilee Hills', 'Hyderabad', 'Telangana', 1),
(1002, 'Apollo Reach', 'Warangal', 'Telangana', 1),
(2001, 'Manipal Central', 'Bengaluru', 'Karnataka', 2);

// Diagnosis Groups
INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP (DIAGNOSIS_GROUP_ID, DIAGNOSIS_GROUP_NAME) VALUES
('DG-CARD', 'Cardiology'),
('DG-ORTH', 'Orthopedics'),
('DG-SURG', 'General Surgery');

// Treatments (Cardiology=1, Orthopedics=2, General Surgery=3)
INSERT INTO SNOW_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, STANDARD_COST, DIAGNOSIS_GROUP_KEY) VALUES
(501, 'Coronary Angioplasty', 150000.00, 1),
(502, 'Knee Replacement', 220000.00, 2),
(503, 'Appendectomy', 45000.00, 3);

// TASK 9: BUILD & LOAD SNOWFLAKE FACT TABLE

CREATE OR REPLACE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_KEY NUMBER REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),
    TREATMENT_KEY NUMBER REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY),
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2)
);

INSERT INTO SNOW_FACT_CLAIMS (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT C.CLAIM_ID, C.CLAIM_DATE, C.PATIENT_ID, H.HOSPITAL_KEY, T.TREATMENT_KEY, C.CLAIMED_AMOUNT, C.APPROVED_AMOUNT
FROM (
    SELECT 'CLM-9001' AS CLAIM_ID, '2026-06-01'::DATE AS CLAIM_DATE, 701 AS PATIENT_ID, 1001 AS HOSPITAL_ID, 501 AS TREATMENT_ID, 160000.00 AS CLAIMED_AMOUNT, 150000.00 AS APPROVED_AMOUNT
    UNION ALL SELECT 'CLM-9002', '2026-06-05', 702, 1002, 503, 50000.00, 45000.00
    UNION ALL SELECT 'CLM-9003', '2026-06-10', 703, 2001, 502, 230000.00, 220000.00
    UNION ALL SELECT 'CLM-9004', '2026-06-12', 701, 1001, 503, 48000.00, 45000.00
) C
JOIN SNOW_DIM_HOSPITAL H ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT T ON C.TREATMENT_ID = T.TREATMENT_ID;

// TASK 10: STAR SCHEMA - Specialty Claims Analysis (1-hop join)

SELECT
    T.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_TREATMENT T ON F.TREATMENT_KEY = T.TREATMENT_KEY
GROUP BY T.DIAGNOSIS_GROUP_NAME
ORDER BY T.DIAGNOSIS_GROUP_NAME;

// TASK 11: SNOWFLAKE SCHEMA - Specialty Claims Analysis (multi-hop join)

SELECT
    DG.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_TREATMENT T ON F.TREATMENT_KEY = T.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP DG ON T.DIAGNOSIS_GROUP_KEY = DG.DIAGNOSIS_GROUP_KEY
GROUP BY DG.DIAGNOSIS_GROUP_NAME
ORDER BY DG.DIAGNOSIS_GROUP_NAME;

// TASK 12: NETWORK DIRECTOR PERFORMANCE REPORT

// Star Schema version
SELECT
    H.NETWORK_DIRECTOR,
    COUNT(*) AS TOTAL_CLAIMS_HANDLED,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.NETWORK_DIRECTOR
ORDER BY TOTAL_APPROVED_AMOUNT DESC;

// Snowflake Schema version
SELECT
    N.NETWORK_DIRECTOR,
    COUNT(*) AS TOTAL_CLAIMS_HANDLED,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK N ON H.NETWORK_KEY = N.NETWORK_KEY
GROUP BY N.NETWORK_DIRECTOR
ORDER BY TOTAL_APPROVED_AMOUNT DESC;

// TASK 13: MASTER DATA UPDATE TEST - Network Director Change

// Star Schema: Must update multiple rows
UPDATE STAR_DIM_HOSPITAL
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group';

// Verify: 2 rows updated
SELECT HOSPITAL_ID, HOSPITAL_NAME, NETWORK_NAME, NETWORK_DIRECTOR
FROM STAR_DIM_HOSPITAL
ORDER BY HOSPITAL_ID;

// Snowflake Schema: Only 1 row to update
UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group';

// Verify: 1 row updated
SELECT NETWORK_NAME, NETWORK_DIRECTOR
FROM SNOW_DIM_NETWORK
ORDER BY NETWORK_KEY;

// Maintenance effort comparison
SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS UPDATED_TABLE, 2 AS ROWS_UPDATED, 'Higher (Multiple rows)' AS MAINTENANCE_EFFORT
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK', 1, 'Lower (Single row)';

// TASK 14: FULL ARCHITECTURE RECORD AUDIT

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_HOSPITAL
UNION ALL SELECT 'Star Schema', 'STAR_DIM_TREATMENT', COUNT(*) FROM STAR_DIM_TREATMENT
UNION ALL SELECT 'Star Schema', 'STAR_FACT_CLAIMS', COUNT(*) FROM STAR_FACT_CLAIMS
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK', COUNT(*) FROM SNOW_DIM_NETWORK
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_HOSPITAL', COUNT(*) FROM SNOW_DIM_HOSPITAL
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_DIAGNOSIS_GROUP', COUNT(*) FROM SNOW_DIM_DIAGNOSIS_GROUP
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_TREATMENT', COUNT(*) FROM SNOW_DIM_TREATMENT
UNION ALL SELECT 'Snowflake Schema', 'SNOW_FACT_CLAIMS', COUNT(*) FROM SNOW_FACT_CLAIMS;