// PROJECT 13: Enterprise Retail Analytics
// Star Schema vs Snowflake Schema Implementation
// Modules: 4.3a (Star Schema), 4.3b (Snowflake Schema)

// TASK 1: CREATE DATABASE AND SCHEMA

CREATE OR REPLACE WAREHOUSE PROJECT13_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT13_WH;

CREATE OR REPLACE DATABASE RETAIL_SCHEMAS_DW;

USE DATABASE RETAIL_SCHEMAS_DW;

CREATE OR REPLACE SCHEMA SCHEMA_COMPARISON;
USE SCHEMA SCHEMA_COMPARISON;

// TASK 2: CREATE STAR SCHEMA - DENORMALIZED STORE DIMENSION

CREATE OR REPLACE TABLE STAR_DIM_STORE (
    STORE_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

// TASK 3: CREATE STAR SCHEMA - DENORMALIZED PRODUCT DIMENSION

CREATE OR REPLACE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);

// TASK 4: LOAD STAR DIMENSIONS & CREATE STAR FACT TABLE

INSERT INTO STAR_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_NAME, REGIONAL_MANAGER) VALUES
(201, 'Metro Flagship', 'Hyderabad', 'Telangana', 'South', 'Rajesh Kumar'),
(202, 'Express Hub', 'Warangal', 'Telangana', 'South', 'Rajesh Kumar'),
(203, 'Coastal Center', 'Vijayawada', 'Andhra Pradesh', 'South', 'Rajesh Kumar'),
(204, 'Western Mart', 'Nagpur', 'Maharashtra', 'West', 'Sunil Verma');

INSERT INTO STAR_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, SUBCATEGORY_NAME, CATEGORY_NAME, UNIT_PRICE) VALUES
(501, 'Laptop Pro', 'Laptops', 'Electronics', 75000.00),
(502, 'Wireless Mouse', 'Accessories', 'Electronics', 1500.00),
(503, 'Ergonomic Chair', 'Office', 'Furniture', 12000.00),
(504, 'Coffee Maker', 'Kitchen', 'Appliances', 4500.00);

CREATE OR REPLACE TABLE STAR_FACT_SALES (
    SALES_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER REFERENCES STAR_DIM_STORE(STORE_KEY),
    PRODUCT_KEY NUMBER REFERENCES STAR_DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);

// TASK 5: LOAD STAR SCHEMA FACT DATA

INSERT INTO STAR_FACT_SALES (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT T.TRANSACTION_ID, T.TRANSACTION_DATE, T.CUSTOMER_ID, S.STORE_KEY, P.PRODUCT_KEY, T.QUANTITY, T.TOTAL_AMOUNT
FROM (
    SELECT 'TXN-3001' AS TRANSACTION_ID, '2026-05-01'::DATE AS TRANSACTION_DATE, 101 AS CUSTOMER_ID, 201 AS STORE_ID, 501 AS PRODUCT_ID, 1 AS QUANTITY, 75000.00 AS TOTAL_AMOUNT
    UNION ALL SELECT 'TXN-3002', '2026-05-02', 102, 202, 502, 2, 3000.00
    UNION ALL SELECT 'TXN-3003', '2026-05-03', 103, 203, 503, 1, 12000.00
    UNION ALL SELECT 'TXN-3004', '2026-05-04', 104, 201, 504, 1, 4500.00
    UNION ALL SELECT 'TXN-3005', '2026-05-05', 105, 204, 502, 3, 4500.00
) T
JOIN STAR_DIM_STORE S ON T.STORE_ID = S.STORE_ID
JOIN STAR_DIM_PRODUCT P ON T.PRODUCT_ID = P.PRODUCT_ID;

// TASK 6: BUILD SNOWFLAKE SCHEMA - STORE HIERARCHY

CREATE OR REPLACE TABLE SNOW_DIM_REGION (
    REGION_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_STORE (
    STORE_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_KEY NUMBER REFERENCES SNOW_DIM_REGION(REGION_KEY)
);

// TASK 7: BUILD SNOWFLAKE SCHEMA - PRODUCT HIERARCHY

CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY NUMBER REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);

CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);

// TASK 8: POPULATE SNOWFLAKE SCHEMA DIMENSIONS

// Regions
INSERT INTO SNOW_DIM_REGION (REGION_NAME, REGIONAL_MANAGER) VALUES
('South', 'Rajesh Kumar'),
('West', 'Sunil Verma');

// Stores (South=key 1, West=key 2)
INSERT INTO SNOW_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_KEY) VALUES
(201, 'Metro Flagship', 'Hyderabad', 'Telangana', 1),
(202, 'Express Hub', 'Warangal', 'Telangana', 1),
(203, 'Coastal Center', 'Vijayawada', 'Andhra Pradesh', 1),
(204, 'Western Mart', 'Nagpur', 'Maharashtra', 2);

// Categories
INSERT INTO SNOW_DIM_CATEGORY (CATEGORY_NAME) VALUES
('Electronics'),
('Furniture'),
('Appliances');

// Subcategories (Electronics=1, Furniture=2, Appliances=3)
INSERT INTO SNOW_DIM_SUBCATEGORY (SUBCATEGORY_NAME, CATEGORY_KEY) VALUES
('Laptops', 1),
('Accessories', 1),
('Office', 2),
('Kitchen', 3);

// Products (Laptops=1, Accessories=2, Office=3, Kitchen=4)
INSERT INTO SNOW_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, SUBCATEGORY_KEY) VALUES
(501, 'Laptop Pro', 75000.00, 1),
(502, 'Wireless Mouse', 1500.00, 2),
(503, 'Ergonomic Chair', 12000.00, 3),
(504, 'Coffee Maker', 4500.00, 4);

// TASK 9: CREATE SNOWFLAKE FACT TABLE & LOAD DATA

CREATE OR REPLACE TABLE SNOW_FACT_SALES (
    SALES_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER,
    STORE_KEY NUMBER REFERENCES SNOW_DIM_STORE(STORE_KEY),
    PRODUCT_KEY NUMBER REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);

INSERT INTO SNOW_FACT_SALES (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT T.TRANSACTION_ID, T.TRANSACTION_DATE, T.CUSTOMER_ID, S.STORE_KEY, P.PRODUCT_KEY, T.QUANTITY, T.TOTAL_AMOUNT
FROM (
    SELECT 'TXN-3001' AS TRANSACTION_ID, '2026-05-01'::DATE AS TRANSACTION_DATE, 101 AS CUSTOMER_ID, 201 AS STORE_ID, 501 AS PRODUCT_ID, 1 AS QUANTITY, 75000.00 AS TOTAL_AMOUNT
    UNION ALL SELECT 'TXN-3002', '2026-05-02', 102, 202, 502, 2, 3000.00
    UNION ALL SELECT 'TXN-3003', '2026-05-03', 103, 203, 503, 1, 12000.00
    UNION ALL SELECT 'TXN-3004', '2026-05-04', 104, 201, 504, 1, 4500.00
    UNION ALL SELECT 'TXN-3005', '2026-05-05', 105, 204, 502, 3, 4500.00
) T
JOIN SNOW_DIM_STORE S ON T.STORE_ID = S.STORE_ID
JOIN SNOW_DIM_PRODUCT P ON T.PRODUCT_ID = P.PRODUCT_ID;

// TASK 10: STAR SCHEMA ANALYTICS - Revenue by Region & Category

SELECT
    S.REGION_NAME,
    P.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES F
JOIN STAR_DIM_STORE S ON F.STORE_KEY = S.STORE_KEY
JOIN STAR_DIM_PRODUCT P ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY S.REGION_NAME, P.CATEGORY_NAME
ORDER BY S.REGION_NAME, TOTAL_REVENUE DESC;

// TASK 11: SNOWFLAKE SCHEMA ANALYTICS - Same metrics via normalized joins

SELECT
    R.REGION_NAME,
    C.CATEGORY_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES F
JOIN SNOW_DIM_STORE S ON F.STORE_KEY = S.STORE_KEY
JOIN SNOW_DIM_REGION R ON S.REGION_KEY = R.REGION_KEY
JOIN SNOW_DIM_PRODUCT P ON F.PRODUCT_KEY = P.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY SC ON P.SUBCATEGORY_KEY = SC.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY C ON SC.CATEGORY_KEY = C.CATEGORY_KEY
GROUP BY R.REGION_NAME, C.CATEGORY_NAME
ORDER BY R.REGION_NAME, TOTAL_REVENUE DESC;

// TASK 12: ARCHITECTURAL COMPARISON

SELECT 'Dimension Normalization Level' AS METRIC, 'Denormalized (Flat)' AS STAR_SCHEMA, 'Normalized (Hierarchical)' AS SNOWFLAKE_SCHEMA
UNION ALL SELECT 'Total Dimension Tables', '2 Tables', '5 Tables'
UNION ALL SELECT 'Joins for Category Revenue', '2 Joins (Fact + 2 Dims)', '4 Joins (Fact + 4 Dims)'
UNION ALL SELECT 'Data Redundancy', 'Higher (Repeated text)', 'Lower (Normalized IDs)'
UNION ALL SELECT 'Query Simplicity', 'High (Simple GROUP BY)', 'Lower (Requires nested FKs)';

// TASK 13: REGIONAL MANAGER SALES PERFORMANCE

SELECT
    S.REGIONAL_MANAGER,
    SUM(F.QUANTITY) AS TOTAL_ITEMS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES F
JOIN STAR_DIM_STORE S ON F.STORE_KEY = S.STORE_KEY
GROUP BY S.REGIONAL_MANAGER
ORDER BY TOTAL_SALES_AMOUNT DESC;

// TASK 14: FULL WAREHOUSE AUDIT - RECORD COUNT VERIFICATION

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_STORE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_STORE
UNION ALL SELECT 'Star Schema', 'STAR_DIM_PRODUCT', COUNT(*) FROM STAR_DIM_PRODUCT
UNION ALL SELECT 'Star Schema', 'STAR_FACT_SALES', COUNT(*) FROM STAR_FACT_SALES
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_REGION', COUNT(*) FROM SNOW_DIM_REGION
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_STORE', COUNT(*) FROM SNOW_DIM_STORE
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_CATEGORY', COUNT(*) FROM SNOW_DIM_CATEGORY
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_SUBCATEGORY', COUNT(*) FROM SNOW_DIM_SUBCATEGORY
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_PRODUCT', COUNT(*) FROM SNOW_DIM_PRODUCT
UNION ALL SELECT 'Snowflake Schema', 'SNOW_FACT_SALES', COUNT(*) FROM SNOW_FACT_SALES;