// PROJECT 14B: Financial Gateway — Medallion Lakehouse & Snapshot Auditing
// Lakehouse Architecture: Bronze > Silver > Gold + Time-Travel
// Module: 4.4b

// TASK 1: BRONZE LAYER SETUP & INGESTION

CREATE OR REPLACE WAREHOUSE PROJECT14B_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE PROJECT14B_WH;

CREATE OR REPLACE DATABASE FINTECH_LAKEHOUSE;

USE DATABASE FINTECH_LAKEHOUSE;

CREATE OR REPLACE SCHEMA PAYMENT_PIPELINE;
USE SCHEMA PAYMENT_PIPELINE;

// Bronze Layer: Raw JSON payloads
CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
    RAW_PAYLOAD VARIANT,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

// Ingest 8 raw payment gateway JSON records
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-901","txn_time":"2026-07-10T10:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":50000.00,"fee_pct":2.5,"status":"APPROVED"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-902","txn_time":"2026-07-10T10:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":12000.00,"fee_pct":3.0,"status":"APPROVED"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-903","txn_time":"2026-07-10T11:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":25000.00,"fee_pct":2.5,"status":"PENDING"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-904","txn_time":"2026-07-10T11:30:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":8500.00,"fee_pct":1.8,"status":"APPROVED"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-905","txn_time":"2026-07-10T12:00:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":45000.00,"fee_pct":3.0,"status":"DECLINED"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-906","txn_time":"2026-07-10T12:30:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":150000.00,"fee_pct":2.5,"status":"APPROVED"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-907","txn_time":"2026-07-10T13:00:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":3200.00,"fee_pct":1.8,"status":"APPROVED"}');
INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD) SELECT PARSE_JSON('{"txn_id":"TXN-908","txn_time":"2026-07-10T13:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":67000.00,"fee_pct":3.0,"status":"PENDING"}');

// Verify
SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT FROM BRONZE_PAYMENT_PAYLOADS;

// TASK 2: SILVER LAYER ETL & FEE COMPUTATIONS

CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    TXN_ID VARCHAR(50),
    TXN_TIME TIMESTAMP,
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(100),
    MASKED_CARD VARCHAR(20),
    GROSS_AMOUNT NUMBER(12,2),
    FEE_PCT NUMBER(5,2),
    PROCESSING_FEE NUMBER(12,2),
    NET_SETTLEMENT_AMOUNT NUMBER(12,2),
    STATUS VARCHAR(20)
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR,
    RAW_PAYLOAD:txn_time::TIMESTAMP,
    RAW_PAYLOAD:merchant_id::NUMBER,
    RAW_PAYLOAD:merchant_name::VARCHAR,
    CONCAT('XXXX-XXXX-XXXX-', RIGHT(RAW_PAYLOAD:card_number::VARCHAR, 4)),
    RAW_PAYLOAD:amount::NUMBER(12,2),
    RAW_PAYLOAD:fee_pct::NUMBER(5,2),
    ROUND(RAW_PAYLOAD:amount::NUMBER(12,2) * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100), 2),
    ROUND(RAW_PAYLOAD:amount::NUMBER(12,2) - (RAW_PAYLOAD:amount::NUMBER(12,2) * (RAW_PAYLOAD:fee_pct::NUMBER(5,2) / 100)), 2),
    RAW_PAYLOAD:status::VARCHAR
FROM BRONZE_PAYMENT_PAYLOADS;

// Verify Silver layer
SELECT TXN_ID, MERCHANT_ID, MERCHANT_NAME, MASKED_CARD, GROSS_AMOUNT, PROCESSING_FEE, NET_SETTLEMENT_AMOUNT, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_TIME;

// TASK 3: GOLD LAYER FINANCIAL AGGREGATIONS (APPROVED only)

CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(100),
    TOTAL_APPROVED_GROSS NUMBER(12,2),
    TOTAL_GATEWAY_FEES NUMBER(12,2),
    TOTAL_NET_PAYOUT NUMBER(12,2),
    APPROVED_COUNT NUMBER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT),
    SUM(PROCESSING_FEE),
    SUM(NET_SETTLEMENT_AMOUNT),
    COUNT(*)
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY MERCHANT_ID, MERCHANT_NAME;

// Verify Gold layer
SELECT * FROM GOLD_MERCHANT_SETTLEMENTS ORDER BY MERCHANT_ID;

// TASK 4: DATA CORRUPTION SIMULATION & TIME-TRAVEL INSPECTION

// Simulate accidental corruption: set TechZone APPROVED → REFUNDED
UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone' AND STATUS = 'APPROVED';

// Capture the query ID of the corruption for Time-Travel recovery
SET corruption_query_id = (SELECT LAST_QUERY_ID());

// Verify corruption happened
SELECT TXN_ID, MERCHANT_NAME, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone';

// Time-Travel: Inspect pre-corruption state
SELECT TXN_ID, MERCHANT_NAME, GROSS_AMOUNT, STATUS
FROM SILVER_CLEANED_TRANSACTIONS BEFORE (STATEMENT => $corruption_query_id)
WHERE MERCHANT_NAME = 'TechZone' AND STATUS = 'APPROVED';

// TASK 5: TIME-TRAVEL RECOVERY EXECUTION

// Revert corrupted records using Time-Travel data
MERGE INTO SILVER_CLEANED_TRANSACTIONS AS target
USING (
    SELECT TXN_ID, STATUS
    FROM SILVER_CLEANED_TRANSACTIONS BEFORE (STATEMENT => $corruption_query_id)
    WHERE MERCHANT_NAME = 'TechZone' AND STATUS = 'APPROVED'
) AS source
ON target.TXN_ID = source.TXN_ID
WHEN MATCHED THEN UPDATE SET target.STATUS = source.STATUS;

// Verify recovery
SELECT
    MERCHANT_NAME,
    SUM(CASE WHEN STATUS = 'APPROVED' THEN 1 ELSE 0 END) AS APPROVED_COUNT,
    SUM(CASE WHEN STATUS = 'REFUNDED' THEN 1 ELSE 0 END) AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;

// TASK 6: END-TO-END PIPELINE RECONCILIATION AUDIT

SELECT
    (SELECT SUM(RAW_PAYLOAD:amount::NUMBER(12,2)) FROM BRONZE_PAYMENT_PAYLOADS) AS BRONZE_GROSS_SUM,
    (SELECT SUM(GROSS_AMOUNT) FROM SILVER_CLEANED_TRANSACTIONS) AS SILVER_GROSS_SUM,
    (SELECT SUM(TOTAL_APPROVED_GROSS) FROM GOLD_MERCHANT_SETTLEMENTS) AS GOLD_GROSS_SUM,
    CASE
        WHEN (SELECT SUM(RAW_PAYLOAD:amount::NUMBER(12,2)) FROM BRONZE_PAYMENT_PAYLOADS)
           = (SELECT SUM(GROSS_AMOUNT) FROM SILVER_CLEANED_TRANSACTIONS)
        THEN 'TRUE'
        ELSE 'FALSE'
    END AS DATA_MATCH_FLAG;