// PROJECT 7: Hospital Healthcare Analytics
// Kimball Dimensional Modeling in Snowflake
// Two Business Processes: Patient Admissions & Medical Billing

// TASK 1: CREATE SNOWFLAKE ENVIRONMENT

CREATE OR REPLACE WAREHOUSE HEALTHCARE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE HEALTHCARE_WH;

CREATE OR REPLACE DATABASE HEALTHCARE_DW;

USE DATABASE HEALTHCARE_DW;

CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA ANALYTICS;

// TASK 1.1: CREATE STAGING TABLES & LOAD DATA

USE SCHEMA STAGING;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
    FILE_FORMAT = CSV_FORMAT;

// Staging: PATIENTS
CREATE OR REPLACE TABLE STG_PATIENTS (
    PATIENT_ID VARCHAR(10),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(10),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

// Staging: DOCTORS
CREATE OR REPLACE TABLE STG_DOCTORS (
    DOCTOR_ID VARCHAR(10),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

// Staging: HOSPITALS
CREATE OR REPLACE TABLE STG_HOSPITALS (
    HOSPITAL_ID VARCHAR(10),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);

// Staging: DEPARTMENTS
CREATE OR REPLACE TABLE STG_DEPARTMENTS (
    DEPARTMENT_ID VARCHAR(10),
    DEPARTMENT_NAME VARCHAR(100)
);

// Staging: TREATMENTS
CREATE OR REPLACE TABLE STG_TREATMENTS (
    TREATMENT_ID VARCHAR(10),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(50)
);

// Staging: ADMISSIONS
CREATE OR REPLACE TABLE STG_ADMISSIONS (
    ADMISSION_ID VARCHAR(10),
    PATIENT_ID VARCHAR(10),
    DOCTOR_ID VARCHAR(10),
    HOSPITAL_ID VARCHAR(10),
    DEPARTMENT_ID VARCHAR(10),
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE
);

// Staging: BILLING
CREATE OR REPLACE TABLE STG_BILLING (
    BILLING_ID VARCHAR(10),
    PATIENT_ID VARCHAR(10),
    DOCTOR_ID VARCHAR(10),
    HOSPITAL_ID VARCHAR(10),
    DEPARTMENT_ID VARCHAR(10),
    TREATMENT_ID VARCHAR(10),
    BILLING_DATE DATE,
    QUANTITY NUMBER,
    TREATMENT_AMOUNT NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2)
);

// TASK 1.2: LOAD STAGING DATA

// Load Patients (6 rows)
INSERT INTO STG_PATIENTS VALUES
('P101','Amit Sharma','Male','Hyderabad','Telangana'),
('P102','Priya Reddy','Female','Warangal','Telangana'),
('P103','Rahul Verma','Male','Vijayawada','Andhra Pradesh'),
('P104','Neha Patel','Female','Hyderabad','Telangana'),
('P105','Arjun Gupta','Male','Nagpur','Maharashtra'),
('P106','Sneha Rao','Female','Bengaluru','Karnataka');

// Load Doctors (4 rows)
INSERT INTO STG_DOCTORS VALUES
('D201','Dr. Rao','Cardiology'),
('D202','Dr. Mehta','Neurology'),
('D203','Dr. Kumar','Orthopedics'),
('D204','Dr. Sharma','General Medicine');

// Load Hospitals (3 rows)
INSERT INTO STG_HOSPITALS VALUES
('H301','KMIT Hospital','Hyderabad','Telangana','South'),
('H302','City Care Hospital','Warangal','Telangana','South'),
('H303','Apollo Care','Vijayawada','Andhra Pradesh','South');

// Load Departments (4 rows)
INSERT INTO STG_DEPARTMENTS VALUES
('DP401','Cardiology'),
('DP402','Neurology'),
('DP403','Orthopedics'),
('DP404','General Medicine');

// Load Treatments (6 rows)
INSERT INTO STG_TREATMENTS VALUES
('T501','ECG','Diagnostic'),
('T502','MRI Scan','Diagnostic'),
('T503','X-Ray','Diagnostic'),
('T504','Consultation','Consultation'),
('T505','Physiotherapy','Therapy'),
('T506','Blood Test','Diagnostic');

// Load Admissions (10 rows)
INSERT INTO STG_ADMISSIONS VALUES
('A001','P101','D201','H301','DP401','2026-01-05','2026-01-08'),
('A002','P102','D202','H302','DP402','2026-01-10','2026-01-15'),
('A003','P103','D203','H303','DP403','2026-01-12','2026-01-18'),
('A004','P104','D204','H301','DP404','2026-01-20','2026-01-22'),
('A005','P105','D201','H301','DP401','2026-02-03','2026-02-07'),
('A006','P106','D202','H302','DP402','2026-02-08','2026-02-12'),
('A007','P101','D201','H301','DP401','2026-02-15','2026-02-20'),
('A008','P102','D202','H302','DP402','2026-03-02','2026-03-06'),
('A009','P103','D203','H303','DP403','2026-03-10','2026-03-16'),
('A010','P104','D204','H301','DP404','2026-03-18','2026-03-20');

// Load Billing (22 rows - multiple treatments per admission)
INSERT INTO STG_BILLING VALUES
('B001','P101','D201','H301','DP401','T501','2026-01-05',1,800.00,100.00,700.00),
('B002','P101','D201','H301','DP401','T506','2026-01-06',1,600.00,100.00,500.00),
('B003','P102','D202','H302','DP402','T502','2026-01-10',1,3500.00,200.00,3300.00),
('B004','P102','D202','H302','DP402','T504','2026-01-11',1,1000.00,100.00,900.00),
('B005','P102','D202','H302','DP402','T506','2026-01-12',1,900.00,100.00,800.00),
('B006','P103','D203','H303','DP403','T503','2026-01-12',1,2200.00,200.00,2000.00),
('B007','P103','D203','H303','DP403','T505','2026-01-14',2,2100.00,100.00,2000.00),
('B008','P104','D204','H301','DP404','T504','2026-01-20',1,1500.00,150.00,1350.00),
('B009','P104','D204','H301','DP404','T506','2026-01-21',1,800.00,100.00,700.00),
('B010','P105','D201','H301','DP401','T501','2026-02-03',1,900.00,100.00,800.00),
('B011','P105','D201','H301','DP401','T506','2026-02-04',1,500.00,100.00,400.00),
('B012','P106','D202','H302','DP402','T502','2026-02-08',1,3000.00,200.00,2800.00),
('B013','P106','D202','H302','DP402','T504','2026-02-09',1,700.00,100.00,600.00),
('B014','P106','D202','H302','DP402','T506','2026-02-10',1,600.00,100.00,500.00),
('B015','P101','D201','H301','DP401','T501','2026-02-15',1,1200.00,100.00,1100.00),
('B016','P101','D201','H301','DP401','T505','2026-02-17',1,900.00,100.00,800.00),
('B017','P102','D202','H302','DP402','T504','2026-03-02',1,700.00,100.00,600.00),
('B018','P102','D202','H302','DP402','T506','2026-03-03',1,500.00,100.00,400.00),
('B019','P103','D203','H303','DP403','T503','2026-03-10',1,1000.00,100.00,900.00),
('B020','P103','D203','H303','DP403','T505','2026-03-12',1,600.00,100.00,500.00),
('B021','P104','D204','H301','DP404','T504','2026-03-18',1,800.00,100.00,700.00),
('B022','P104','D204','H301','DP404','T506','2026-03-19',1,450.00,100.00,350.00);

// Verify staging loads
SELECT 'Patients Loaded' AS STATUS, COUNT(*) AS ROW_COUNT FROM STG_PATIENTS
UNION ALL SELECT 'Doctors Loaded', COUNT(*) FROM STG_DOCTORS
UNION ALL SELECT 'Hospitals Loaded', COUNT(*) FROM STG_HOSPITALS
UNION ALL SELECT 'Departments Loaded', COUNT(*) FROM STG_DEPARTMENTS
UNION ALL SELECT 'Treatments Loaded', COUNT(*) FROM STG_TREATMENTS
UNION ALL SELECT 'Admissions Loaded', COUNT(*) FROM STG_ADMISSIONS
UNION ALL SELECT 'Billing Loaded', COUNT(*) FROM STG_BILLING;

// TASK 2: CREATE DIMENSION TABLES (with Surrogate Keys)

USE SCHEMA ANALYTICS;

// Create Sequences for Surrogate Keys
CREATE OR REPLACE SEQUENCE SEQ_PATIENT START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE SEQ_DOCTOR START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE SEQ_HOSPITAL START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE SEQ_DEPARTMENT START = 1 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE SEQ_TREATMENT START = 1 INCREMENT = 1;

// DIM_PATIENT
CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY NUMBER PRIMARY KEY DEFAULT SEQ_PATIENT.NEXTVAL,
    PATIENT_ID VARCHAR(10),
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(10),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

// DIM_DOCTOR
CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY NUMBER PRIMARY KEY DEFAULT SEQ_DOCTOR.NEXTVAL,
    DOCTOR_ID VARCHAR(10),
    DOCTOR_NAME VARCHAR(100),
    SPECIALIZATION VARCHAR(100)
);

// DIM_HOSPITAL
CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER PRIMARY KEY DEFAULT SEQ_HOSPITAL.NEXTVAL,
    HOSPITAL_ID VARCHAR(10),
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50)
);

// DIM_DEPARTMENT
CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY NUMBER PRIMARY KEY DEFAULT SEQ_DEPARTMENT.NEXTVAL,
    DEPARTMENT_ID VARCHAR(10),
    DEPARTMENT_NAME VARCHAR(100)
);

// DIM_TREATMENT
CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY NUMBER PRIMARY KEY DEFAULT SEQ_TREATMENT.NEXTVAL,
    TREATMENT_ID VARCHAR(10),
    TREATMENT_NAME VARCHAR(100),
    TREATMENT_CATEGORY VARCHAR(50)
);

// TASK 3: LOAD DIMENSION DATA

INSERT INTO DIM_PATIENT (PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE)
SELECT PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE
FROM STAGING.STG_PATIENTS;

INSERT INTO DIM_DOCTOR (DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION)
SELECT DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION
FROM STAGING.STG_DOCTORS;

INSERT INTO DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION)
SELECT HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION
FROM STAGING.STG_HOSPITALS;

INSERT INTO DIM_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM STAGING.STG_DEPARTMENTS;

INSERT INTO DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY)
SELECT TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY
FROM STAGING.STG_TREATMENTS;

// Verify dimension loads
SELECT 'Patients Loaded' AS STATUS, COUNT(*) AS COUNT FROM DIM_PATIENT
UNION ALL SELECT 'Doctors Loaded', COUNT(*) FROM DIM_DOCTOR
UNION ALL SELECT 'Hospitals Loaded', COUNT(*) FROM DIM_HOSPITAL
UNION ALL SELECT 'Departments Loaded', COUNT(*) FROM DIM_DEPARTMENT
UNION ALL SELECT 'Treatments Loaded', COUNT(*) FROM DIM_TREATMENT;

// TASK 4: CREATE & LOAD DIM_DATE (2026-01-01 to 2026-03-31)

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR(20),
    WEEK_NO NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(5),
    YEAR NUMBER
);

INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE), 'YYYYMMDD')) AS DATE_KEY,
    DATEADD(DAY, SEQ4(), '2026-01-01'::DATE) AS FULL_DATE,
    DAY(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS DAY,
    DAYNAME(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS DAY_NAME,
    WEEKOFYEAR(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS WEEK_NO,
    MONTH(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS MONTH,
    MONTHNAME(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS MONTH_NAME,
    CONCAT('Q', QUARTER(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE))) AS QUARTER,
    YEAR(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS YEAR
FROM TABLE(GENERATOR(ROWCOUNT => 90))
WHERE DATEADD(DAY, SEQ4(), '2026-01-01'::DATE) <= '2026-03-31'::DATE;

// Verify DIM_DATE
SELECT COUNT(*) AS DATE_ROWS FROM DIM_DATE;

SELECT * FROM DIM_DATE ORDER BY DATE_KEY LIMIT 5;

// TASK 5: IDENTIFY BUSINESS PROCESSES
// TASK 6: CREATE FACT_ADMISSION

CREATE OR REPLACE SEQUENCE SEQ_ADMISSION START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY NUMBER PRIMARY KEY DEFAULT SEQ_ADMISSION.NEXTVAL,
    PATIENT_KEY NUMBER REFERENCES DIM_PATIENT(PATIENT_KEY),
    DOCTOR_KEY NUMBER REFERENCES DIM_DOCTOR(DOCTOR_KEY),
    HOSPITAL_KEY NUMBER REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),
    DEPARTMENT_KEY NUMBER REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),
    DATE_KEY NUMBER REFERENCES DIM_DATE(DATE_KEY),
    ADMISSION_COUNT NUMBER,
    LENGTH_OF_STAY NUMBER
);

// TASK 7: DEFINE FACT_ADMISSION GRAIN
// TASK 8: CREATE FACT_BILLING

CREATE OR REPLACE SEQUENCE SEQ_BILLING START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY NUMBER PRIMARY KEY DEFAULT SEQ_BILLING.NEXTVAL,
    PATIENT_KEY NUMBER REFERENCES DIM_PATIENT(PATIENT_KEY),
    DOCTOR_KEY NUMBER REFERENCES DIM_DOCTOR(DOCTOR_KEY),
    HOSPITAL_KEY NUMBER REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),
    DEPARTMENT_KEY NUMBER REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),
    TREATMENT_KEY NUMBER REFERENCES DIM_TREATMENT(TREATMENT_KEY),
    DATE_KEY NUMBER REFERENCES DIM_DATE(DATE_KEY),
    QUANTITY NUMBER,
    TREATMENT_AMOUNT NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2)
);

// TASK 9: DEFINE FACT_BILLING GRAIN
// TASK 10: IDENTIFY MEASURES
// TASK 11: LOAD FACT_ADMISSION

INSERT INTO FACT_ADMISSION (PATIENT_KEY, DOCTOR_KEY, HOSPITAL_KEY, DEPARTMENT_KEY, DATE_KEY, ADMISSION_COUNT, LENGTH_OF_STAY)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    DT.DATE_KEY,
    1 AS ADMISSION_COUNT,
    DATEDIFF(DAY, A.ADMISSION_DATE, A.DISCHARGE_DATE) AS LENGTH_OF_STAY
FROM STAGING.STG_ADMISSIONS A
JOIN DIM_PATIENT P ON A.PATIENT_ID = P.PATIENT_ID
JOIN DIM_DOCTOR D ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN DIM_HOSPITAL H ON A.HOSPITAL_ID = H.HOSPITAL_ID
JOIN DIM_DEPARTMENT DP ON A.DEPARTMENT_ID = DP.DEPARTMENT_ID
JOIN DIM_DATE DT ON DT.FULL_DATE = A.ADMISSION_DATE;

// Verify
SELECT COUNT(*) AS FACT_ADMISSION_ROWS FROM FACT_ADMISSION;

// TASK 11.1: LOAD FACT_BILLING

INSERT INTO FACT_BILLING (PATIENT_KEY, DOCTOR_KEY, HOSPITAL_KEY, DEPARTMENT_KEY, TREATMENT_KEY, DATE_KEY, QUANTITY, TREATMENT_AMOUNT, DISCOUNT, NET_AMOUNT)
SELECT
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    T.TREATMENT_KEY,
    DT.DATE_KEY,
    B.QUANTITY,
    B.TREATMENT_AMOUNT,
    B.DISCOUNT,
    B.NET_AMOUNT
FROM STAGING.STG_BILLING B
JOIN DIM_PATIENT P ON B.PATIENT_ID = P.PATIENT_ID
JOIN DIM_DOCTOR D ON B.DOCTOR_ID = D.DOCTOR_ID
JOIN DIM_HOSPITAL H ON B.HOSPITAL_ID = H.HOSPITAL_ID
JOIN DIM_DEPARTMENT DP ON B.DEPARTMENT_ID = DP.DEPARTMENT_ID
JOIN DIM_TREATMENT T ON B.TREATMENT_ID = T.TREATMENT_ID
JOIN DIM_DATE DT ON DT.FULL_DATE = B.BILLING_DATE;

// Verify
SELECT COUNT(*) AS FACT_BILLING_ROWS FROM FACT_BILLING;

// TASK 12: CONFORMED DIMENSIONS & STAR SCHEMA
// TASK 13: ADMISSION ANALYTICS - Hospital-wise Admissions

SELECT
    H.HOSPITAL_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

// TASK 13.1: Admissions by Department

SELECT
    DP.DEPARTMENT_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS,
    ROUND(AVG(F.LENGTH_OF_STAY), 1) AS AVG_STAY_DAYS
FROM FACT_ADMISSION F
JOIN DIM_DEPARTMENT DP ON F.DEPARTMENT_KEY = DP.DEPARTMENT_KEY
GROUP BY DP.DEPARTMENT_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

// TASK 13.2: Admissions by Doctor

SELECT
    D.DOCTOR_NAME,
    D.SPECIALIZATION,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS,
    SUM(F.LENGTH_OF_STAY) AS TOTAL_STAY_DAYS
FROM FACT_ADMISSION F
JOIN DIM_DOCTOR D ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME, D.SPECIALIZATION
ORDER BY TOTAL_ADMISSIONS DESC;

// TASK 13.3: Monthly Admissions

SELECT
    DT.MONTH_NAME,
    DT.YEAR,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DATE DT ON F.DATE_KEY = DT.DATE_KEY
GROUP BY DT.MONTH_NAME, DT.YEAR, DT.MONTH
ORDER BY DT.MONTH;

// TASK 14: HOSPITAL REVENUE ANALYTICS

SELECT
    H.HOSPITAL_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_REVENUE DESC;

// TASK 15: MONTHLY REVENUE

SELECT
    TO_CHAR(DT.FULL_DATE, 'YYYY-MM') AS MONTH,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DATE DT ON F.DATE_KEY = DT.DATE_KEY
GROUP BY TO_CHAR(DT.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;

// TASK 16: DOCTOR-WISE REVENUE

SELECT
    D.DOCTOR_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DOCTOR D ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC;

// TASK 16.1: Revenue by Treatment

SELECT
    T.TREATMENT_NAME,
    T.TREATMENT_CATEGORY,
    SUM(F.QUANTITY) AS TOTAL_QTY,
    SUM(F.TREATMENT_AMOUNT) AS GROSS_REVENUE,
    SUM(F.DISCOUNT) AS TOTAL_DISCOUNT,
    SUM(F.NET_AMOUNT) AS NET_REVENUE
FROM FACT_BILLING F
JOIN DIM_TREATMENT T ON F.TREATMENT_KEY = T.TREATMENT_KEY
GROUP BY T.TREATMENT_NAME, T.TREATMENT_CATEGORY
ORDER BY NET_REVENUE DESC;

// TASK 16.2: Revenue by Department

SELECT
    DP.DEPARTMENT_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE,
    COUNT(*) AS BILLING_COUNT
FROM FACT_BILLING F
JOIN DIM_DEPARTMENT DP ON F.DEPARTMENT_KEY = DP.DEPARTMENT_KEY
GROUP BY DP.DEPARTMENT_NAME
ORDER BY TOTAL_REVENUE DESC;

// TASK 17: DRILL-ACROSS ANALYSIS
// Compare Total Admissions and Total Revenue by Hospital
// (Using Conformed Dimension: DIM_HOSPITAL)

SELECT
    H.HOSPITAL_NAME,
    A.TOTAL_ADMISSIONS,
    B.TOTAL_REVENUE
FROM DIM_HOSPITAL H
LEFT JOIN (
    SELECT HOSPITAL_KEY, SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY
) A ON H.HOSPITAL_KEY = A.HOSPITAL_KEY
LEFT JOIN (
    SELECT HOSPITAL_KEY, SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY
) B ON H.HOSPITAL_KEY = B.HOSPITAL_KEY
ORDER BY A.TOTAL_ADMISSIONS DESC;

// TASK 18: BUS MATRIX
// ADDITIONAL ANALYTICS

// Patient-wise Total Spend
SELECT
    P.PATIENT_NAME,
    P.CITY,
    SUM(F.NET_AMOUNT) AS TOTAL_SPEND,
    COUNT(*) AS TREATMENTS_RECEIVED
FROM FACT_BILLING F
JOIN DIM_PATIENT P ON F.PATIENT_KEY = P.PATIENT_KEY
GROUP BY P.PATIENT_NAME, P.CITY
ORDER BY TOTAL_SPEND DESC;

// Admission Duration Analysis
SELECT
    P.PATIENT_NAME,
    H.HOSPITAL_NAME,
    D.DOCTOR_NAME,
    DT.FULL_DATE AS ADMISSION_DATE,
    F.LENGTH_OF_STAY
FROM FACT_ADMISSION F
JOIN DIM_PATIENT P ON F.PATIENT_KEY = P.PATIENT_KEY
JOIN DIM_HOSPITAL H ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
JOIN DIM_DOCTOR D ON F.DOCTOR_KEY = D.DOCTOR_KEY
JOIN DIM_DATE DT ON F.DATE_KEY = DT.DATE_KEY
ORDER BY F.LENGTH_OF_STAY DESC;

// Revenue per Admission (Drill-Across by Patient)
SELECT
    P.PATIENT_NAME,
    SUM(A.ADMISSION_COUNT) AS TOTAL_ADMISSIONS,
    SUM(A.LENGTH_OF_STAY) AS TOTAL_STAY_DAYS,
    B.TOTAL_BILLED
FROM FACT_ADMISSION A
JOIN DIM_PATIENT P ON A.PATIENT_KEY = P.PATIENT_KEY
LEFT JOIN (
    SELECT PATIENT_KEY, SUM(NET_AMOUNT) AS TOTAL_BILLED
    FROM FACT_BILLING
    GROUP BY PATIENT_KEY
) B ON P.PATIENT_KEY = B.PATIENT_KEY
GROUP BY P.PATIENT_NAME, B.TOTAL_BILLED
ORDER BY B.TOTAL_BILLED DESC;

// FINAL VERIFICATION

// All table row counts
SELECT 'DIM_PATIENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_PATIENT
UNION ALL SELECT 'DIM_DOCTOR', COUNT(*) FROM DIM_DOCTOR
UNION ALL SELECT 'DIM_HOSPITAL', COUNT(*) FROM DIM_HOSPITAL
UNION ALL SELECT 'DIM_DEPARTMENT', COUNT(*) FROM DIM_DEPARTMENT
UNION ALL SELECT 'DIM_TREATMENT', COUNT(*) FROM DIM_TREATMENT
UNION ALL SELECT 'DIM_DATE', COUNT(*) FROM DIM_DATE
UNION ALL SELECT 'FACT_ADMISSION', COUNT(*) FROM FACT_ADMISSION
UNION ALL SELECT 'FACT_BILLING', COUNT(*) FROM FACT_BILLING;

// Final object list
SHOW TABLES IN SCHEMA HEALTHCARE_DW.ANALYTICS;
