// PROJECT 9: Customer History Management
// SCD Type 1 and Type 2 Implementation in Snowflake
// Topic: 4.2B

// TASK 1: CREATE DATABASE AND SCHEMA

CREATE OR REPLACE WAREHOUSE SCD2_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SCD2_WH;

CREATE OR REPLACE DATABASE SCD_PROJECT;

USE DATABASE SCD_PROJECT;

CREATE OR REPLACE SCHEMA PUBLIC;
USE SCHEMA PUBLIC;

// TASK 2: CREATE SCD TYPE 1 TABLE

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY NUMBER IDENTITY(1,1),
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

// TASK 3: LOAD INITIAL TYPE 1 DATA

INSERT INTO DIM_CUSTOMER_TYPE1 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
VALUES
(101, 'Amit Sharma', 'Hyderabad', 'Telangana', 'Silver', 'Regular'),
(102, 'Priya Reddy', 'Warangal', 'Telangana', 'Gold', 'Premium'),
(103, 'Rahul Verma', 'Vijayawada', 'Andhra Pradesh', 'Silver', 'Regular'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Gold', 'Premium'),
(105, 'Arjun Gupta', 'Nagpur', 'Maharashtra', 'Bronze', 'Regular');

SELECT 'Initial Type 1 Records Loaded Successfully' AS STATUS;
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM DIM_CUSTOMER_TYPE1;

// Display initial state
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

// TASK 4: APPLY SCD TYPE 1 UPDATES (Overwrite)

// Create staging table for updates
CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

INSERT INTO CUSTOMER_UPDATES VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10');

// Apply Type 1 update: OVERWRITE existing records
MERGE INTO DIM_CUSTOMER_TYPE1 T
USING CUSTOMER_UPDATES U
ON T.CUSTOMER_ID = U.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    T.CUSTOMER_NAME = U.CUSTOMER_NAME,
    T.CITY = U.CITY,
    T.STATE = U.STATE,
    T.MEMBERSHIP = U.MEMBERSHIP,
    T.SEGMENT = U.SEGMENT;

// TASK 5: DISPLAY TYPE 1 RESULT

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

// TASK 6: DEMONSTRATE TYPE 1 HISTORY LOSS

SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;

// TASK 7 & 8: CREATE SCD TYPE 2 TABLE

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY NUMBER IDENTITY(1,1),
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

// Verify structure
DESCRIBE TABLE DIM_CUSTOMER_TYPE2;

// TASK 9: LOAD INITIAL TYPE 2 RECORDS

INSERT INTO DIM_CUSTOMER_TYPE2
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(101, 'Amit Sharma', 'Hyderabad', 'Telangana', 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(102, 'Priya Reddy', 'Warangal', 'Telangana', 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(103, 'Rahul Verma', 'Vijayawada', 'Andhra Pradesh', 'Silver', 'Regular', '2026-01-01', '9999-12-31', TRUE),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Gold', 'Premium', '2026-01-01', '9999-12-31', TRUE),
(105, 'Arjun Gupta', 'Nagpur', 'Maharashtra', 'Bronze', 'Regular', '2026-01-01', '9999-12-31', TRUE);

SELECT 'Initial SCD Type 2 Records Loaded' AS STATUS;
SELECT COUNT(*) AS TOTAL_RECORDS FROM DIM_CUSTOMER_TYPE2;
SELECT COUNT(*) AS CURRENT_RECORDS FROM DIM_CUSTOMER_TYPE2 WHERE IS_CURRENT = TRUE;

// TASK 10 & 11: APPLY TYPE 2 CHANGE — CUSTOMER 101

// Step 1: Expire the existing record for Customer 101
UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

// Step 2: Insert new version for Customer 101
INSERT INTO DIM_CUSTOMER_TYPE2
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium', '2026-04-01', '9999-12-31', TRUE);

// Verify Customer 101 history
SELECT
    CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

// TASK 12: APPLY TYPE 2 CHANGE — CUSTOMER 103

// Step 1: Expire the existing record for Customer 103
UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

// Step 2: Insert new version for Customer 103
INSERT INTO DIM_CUSTOMER_TYPE2
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium', '2026-04-05', '9999-12-31', TRUE);

// Verify Customer 103 history
SELECT
    CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

// TASK 13: APPLY TYPE 2 CHANGE — CUSTOMER 104

// Step 1: Expire the existing record for Customer 104
UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

// Step 2: Insert new version for Customer 104
INSERT INTO DIM_CUSTOMER_TYPE2
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
VALUES
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium', '2026-04-10', '9999-12-31', TRUE);

// Verify Customer 104 history
SELECT
    CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

// TASK 14: DISPLAY COMPLETE TYPE 2 HISTORY

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

// TASK 15: DISPLAY CURRENT CUSTOMER RECORDS ONLY

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

// TASK 16: HISTORICAL CUSTOMER ANALYSIS (Point-in-Time Query)

// What was Customer 101's membership on March 15, 2026?
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

// TASK 17: COMPARE TYPE 1 vs TYPE 2

// Type 1: Query Customer 101
SELECT 'TYPE 1' AS SCD_TYPE, CUSTOMER_ID, CITY, MEMBERSHIP,
       NULL AS EFFECTIVE_DATE, NULL AS EXPIRY_DATE, NULL AS IS_CURRENT
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101

UNION ALL

// Type 2: Query Customer 101 (all versions)
SELECT 'TYPE 2', CUSTOMER_ID, CITY, MEMBERSHIP,
       EFFECTIVE_DATE::VARCHAR, EXPIRY_DATE::VARCHAR, IS_CURRENT::VARCHAR
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY SCD_TYPE, EFFECTIVE_DATE;

// TASK 18: FINAL VALIDATION

// SCD Type 1 Record Count
SELECT 'SCD TYPE 1 RECORD COUNT' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_TYPE1;

// SCD Type 2 Record Count
SELECT 'SCD TYPE 2 RECORD COUNT' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_TYPE2;

// SCD Type 2 Current Records
SELECT 'SCD TYPE 2 CURRENT RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE;

// SCD Type 2 Historical Records
SELECT 'SCD TYPE 2 HISTORICAL RECORDS' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE;

// Combined validation summary
SELECT 'TYPE1_TOTAL' AS METRIC, COUNT(*) AS COUNT FROM DIM_CUSTOMER_TYPE1
UNION ALL
SELECT 'TYPE2_TOTAL', COUNT(*) FROM DIM_CUSTOMER_TYPE2
UNION ALL
SELECT 'TYPE2_CURRENT', COUNT(*) FROM DIM_CUSTOMER_TYPE2 WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'TYPE2_HISTORICAL', COUNT(*) FROM DIM_CUSTOMER_TYPE2 WHERE IS_CURRENT = FALSE;
