// PROJECT 2 : RETAIL SALES ANALYTICS

// PHASE 1 - ENVIRONMENT SETUP

// 1. Create Virtual Warehouse
CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RETAIL_WH;

// 2. Create Database
CREATE OR REPLACE DATABASE RETAIL_DB;

// 3. Create Schema
CREATE OR REPLACE SCHEMA SALES_SCHEMA;

USE DATABASE RETAIL_DB;
USE SCHEMA SALES_SCHEMA;

// PHASE 2 - TABLE CREATION & DATA LOADING

// 1. Create File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

// 2. Create Internal Stage
CREATE OR REPLACE STAGE RETAIL_STAGE
    FILE_FORMAT = CSV_FORMAT;

// 3. Create Tables
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

CREATE OR REPLACE TABLE SALES (
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    QUANTITY NUMBER,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);

// 4. Load Data from Stage
COPY INTO CUSTOMERS FROM @RETAIL_STAGE/customers.csv FILE_FORMAT = CSV_FORMAT;
COPY INTO PRODUCTS FROM @RETAIL_STAGE/products.csv FILE_FORMAT = CSV_FORMAT;
COPY INTO BRANCHES FROM @RETAIL_STAGE/branches.csv FILE_FORMAT = CSV_FORMAT;
COPY INTO SALES FROM @RETAIL_STAGE/sales.csv FILE_FORMAT = CSV_FORMAT;

// 5. Verify Data
SELECT COUNT(*) AS CUSTOMER_COUNT FROM CUSTOMERS;
SELECT COUNT(*) AS PRODUCT_COUNT FROM PRODUCTS;
SELECT COUNT(*) AS BRANCH_COUNT FROM BRANCHES;
SELECT COUNT(*) AS SALES_COUNT FROM SALES;

// PHASE 3 - SQL ANALYTICS

// 1. Display All Customers
SELECT * FROM CUSTOMERS;

// 2. Display All Products
SELECT * FROM PRODUCTS;

// 3. Display All Branches
SELECT * FROM BRANCHES;

// 4. Display All Sales Transactions
SELECT * FROM SALES;

// 5. Calculate Total Business Revenue
SELECT
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES;

// 6. Customer-wise Sales Report
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC;

// 7. Branch-wise Revenue Report
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

// 8. Product-wise Revenue Report
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

// 9. Category-wise Revenue Report
SELECT
    P.CATEGORY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

// 10. Highest Revenue Branch
SELECT
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

// 11. Highest Spending Customer
SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;

// 12. Top Three Products by Revenue
SELECT
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

// 13. Top Three Customers by Spending
SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

// PHASE 4 - WINDOW FUNCTIONS

// 1. Rank Customers Based on Total Spending
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING,
    RANK() OVER(ORDER BY SUM(S.TOTAL_AMOUNT) DESC) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

// 2. Rank Branches Based on Total Sales
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER(ORDER BY SUM(S.TOTAL_AMOUNT) DESC) AS BRANCH_RANK
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY BRANCH_RANK;

// 3. Top-Selling Product in Each Category
SELECT
    CATEGORY,
    PRODUCT_NAME,
    TOTAL_REVENUE
FROM (
    SELECT
        P.CATEGORY,
        P.PRODUCT_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,
        ROW_NUMBER() OVER(
            PARTITION BY P.CATEGORY
            ORDER BY SUM(S.TOTAL_AMOUNT) DESC
        ) AS RN
    FROM PRODUCTS P
    JOIN SALES S
        ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
        P.CATEGORY,
        P.PRODUCT_NAME
)
WHERE RN = 1;

// 4. Cumulative Sales Report
SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER(
        ORDER BY SALE_DATE
    ) AS CUMULATIVE_SALES
FROM SALES
ORDER BY SALE_DATE;

// 5. Average Sale Amount
SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) OVER() AS AVERAGE_SALE_AMOUNT
FROM SALES
ORDER BY SALE_DATE;

// PHASE 5 - CTE (COMMON TABLE EXPRESSIONS)

// 1. Customer-wise Revenue Using CTE
WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_REVENUE
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

// 2. Customers Spending Greater Than Average Spending
WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_SPENDING
FROM CUSTOMER_REVENUE
WHERE TOTAL_SPENDING > (
    SELECT AVG(TOTAL_SPENDING)
    FROM CUSTOMER_REVENUE
)
ORDER BY TOTAL_SPENDING DESC;

// PHASE 6 - VIEWS & MATERIALIZED VIEWS

// 1. Create SALES_REPORT View
CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT
    S.SALE_ID,
    S.SALE_DATE,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    P.CATEGORY,
    B.BRANCH_NAME,
    S.QUANTITY,
    S.TOTAL_AMOUNT
FROM SALES S
JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;

// 2. Query SALES_REPORT View
SELECT *
FROM SALES_REPORT
ORDER BY SALE_DATE;

// 3. Create TOP_CUSTOMERS View
CREATE OR REPLACE VIEW TOP_CUSTOMERS AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME;

// 4. Query TOP_CUSTOMERS View
SELECT *
FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENDING DESC;

// 5. Display Top 3 Customers
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_SPENDING
FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;