// PROJECT 8: Customer Profile History Analysis
// Slowly Changing Dimension (SCD) — The Problem
// Topic: 4.2A

// TASK 1: CREATE SNOWFLAKE DATABASE AND SCHEMA

CREATE OR REPLACE WAREHOUSE SCD_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SCD_WH;

CREATE OR REPLACE DATABASE SCD_DEMO;

USE DATABASE SCD_DEMO;

CREATE OR REPLACE SCHEMA PUBLIC;

USE SCHEMA PUBLIC;

// TASK 2: CREATE INITIAL CUSTOMER DIMENSION

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

// TASK 3: LOAD INITIAL CUSTOMER DATA

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
VALUES
(101, 'Amit Sharma', 'Hyderabad', 'Telangana', 'Silver', 'Regular'),
(102, 'Priya Reddy', 'Warangal', 'Telangana', 'Gold', 'Premium'),
(103, 'Rahul Verma', 'Vijayawada', 'Andhra Pradesh', 'Silver', 'Regular'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Gold', 'Premium'),
(105, 'Arjun Gupta', 'Nagpur', 'Maharashtra', 'Bronze', 'Regular');

// Verify load
SELECT 'Initial Customer Records Loaded Successfully' AS STATUS;
SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM DIM_CUSTOMER;

// TASK 4: DISPLAY INITIAL CUSTOMER DIMENSION

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

// TASK 5: LOAD CUSTOMER UPDATES INTO STAGING TABLE

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

INSERT INTO CUSTOMER_UPDATES VALUES
(101, 'Amit Sharma', 'Bengaluru', 'Karnataka', 'Gold', 'Premium'),
(103, 'Rahul Verma', 'Chennai', 'Tamil Nadu', 'Gold', 'Premium'),
(104, 'Neha Patel', 'Hyderabad', 'Telangana', 'Platinum', 'Premium');

// Verify
SELECT 'Customer Update Records Loaded Successfully' AS STATUS;
SELECT COUNT(*) AS RECORDS_RECEIVED FROM CUSTOMER_UPDATES;

// TASK 6: IDENTIFY CHANGED CUSTOMERS

SELECT
    D.CUSTOMER_ID,
    D.CITY AS OLD_CITY,
    U.CITY AS NEW_CITY,
    D.MEMBERSHIP AS OLD_MEMBERSHIP,
    U.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U
    ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHERE D.CITY != U.CITY
   OR D.STATE != U.STATE
   OR D.MEMBERSHIP != U.MEMBERSHIP
   OR D.SEGMENT != U.SEGMENT
ORDER BY D.CUSTOMER_ID;

// TASK 7: IDENTIFY ATTRIBUTE CHANGES (Detailed Change Report)

SELECT
    D.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    D.CITY AS OLD_VALUE,
    U.CITY AS NEW_VALUE
FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHERE D.CITY != U.CITY

UNION ALL

SELECT
    D.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    D.STATE AS OLD_VALUE,
    U.STATE AS NEW_VALUE
FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHERE D.STATE != U.STATE

UNION ALL

SELECT
    D.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    D.MEMBERSHIP AS OLD_VALUE,
    U.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHERE D.MEMBERSHIP != U.MEMBERSHIP

UNION ALL

SELECT
    D.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    D.SEGMENT AS OLD_VALUE,
    U.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER D
JOIN CUSTOMER_UPDATES U ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHERE D.SEGMENT != U.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;

// TASK 8: DEMONSTRATE THE SCD PROBLEM
// Apply updates by overwriting existing dimension records

// Save a snapshot of the BEFORE state for comparison
CREATE OR REPLACE TABLE DIM_CUSTOMER_BEFORE_UPDATE AS
SELECT * FROM DIM_CUSTOMER;

// Now apply the updates (OVERWRITE existing records)
MERGE INTO DIM_CUSTOMER D
USING CUSTOMER_UPDATES U
ON D.CUSTOMER_ID = U.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    D.CUSTOMER_NAME = U.CUSTOMER_NAME,
    D.CITY = U.CITY,
    D.STATE = U.STATE,
    D.MEMBERSHIP = U.MEMBERSHIP,
    D.SEGMENT = U.SEGMENT;

// TASK 9: DISPLAY THE UPDATED DIMENSION

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

// TASK 10: DEMONSTRATE HISTORICAL DATA LOSS

// Query: Where did Customer 101 live before the update?
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;

// TASK 10.1: PROVE THE LOSS BY COMPARING BEFORE vs AFTER

SELECT
    B.CUSTOMER_ID,
    B.CUSTOMER_NAME,
    B.CITY AS ORIGINAL_CITY,
    A.CITY AS CURRENT_CITY,
    B.STATE AS ORIGINAL_STATE,
    A.STATE AS CURRENT_STATE,
    B.MEMBERSHIP AS ORIGINAL_MEMBERSHIP,
    A.MEMBERSHIP AS CURRENT_MEMBERSHIP
FROM DIM_CUSTOMER_BEFORE_UPDATE B
JOIN DIM_CUSTOMER A ON B.CUSTOMER_KEY = A.CUSTOMER_KEY
WHERE B.CITY != A.CITY
   OR B.STATE != A.STATE
   OR B.MEMBERSHIP != A.MEMBERSHIP
ORDER BY B.CUSTOMER_ID;

// TASK 11: BUSINESS IMPACT ANALYSIS
// FINAL SUMMARY QUERY

// Show that only current values exist — no history is preserved
SELECT
    'CURRENT STATE' AS DIMENSION_STATE,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;
